name: Android CI

on:
  push:
    branches: [ main ]  # Runs on pushes to 'main'
  pull_request:
    branches: [ main ]  # Runs on PRs targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted Linux runner

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK (Java 11+ is needed for Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # OpenJDK

      # 3. Make gradlew executable (important!)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build the project (checks if it compiles)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Run unit tests (optional but recommended)
      - name: Run tests
        run: ./gradlew test

      # 6. Run lint checks (optional)
      - name: Run Lint
        run: ./gradlew lint
